AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/LeadingCommentSpace:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/CaseEquality:
  Enabled: false
